application: neutron-drive
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: main.app
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'ndrive.settings'
  
builtins:
- remote_api: on
